### ISSUE TITLE
Cannot type characters '"˜` on the US International keyboard (and others)

### ISSUE THREAD

**Issue by ricardopieper** [zed-industries/feedback#199]
I was recently invited to test Zed, version 0.42.0.

**Describe the bug**

Some characters cannot be typed, specifically '"˜`. My OS is in Brazillian Portuguese, keyboard is Portuguese - Brazillian ABNT2. Instead of typing it, the editor just does nothing, and that popping sound of "invalid action" plays (same sound that plays if you open the terminal and press ESC multiple times).

Some latin characters with diacritics and ç and tilde (like ã) are rendered impossible to type due to this.

Changing the keyboard to English - US International does not solve the problem. 

**To reproduce**
 Try typing any of ``'"`˜``. 

**Expected behavior**
Characters typed as expected.

**Environment:**
macOS 12.4 
architecture arm64

**Logs**

[Zed.log](https://github.com/zed-industries/feedback/files/9021424/Zed.log)

**Comment by mikayla-maki** [comment]
Wow, the single and double quotes aren’t working? That’s wild. I wonder if they’re being sent as those curly smart quotes instead of plain straight quotes.

**Comment by ricardopieper** [comment]
Another thing that might be relevant: It's not just in the code/text editor,  everything that accepts text as input also have this behavior.

**Comment by mikayla-maki** [comment]
Note on the Brazilian ABNT2 layout, when typing the `"`character the expected behavior is that either you type a letter, which it adds a diacritic to (e.g. é), or you hit `enter` and it types the `"`. May be related to https://github.com/zed-industries/feedback/issues/7 in how Zed currently doesn't hook into OS support for symbols.

**Comment by lucastrvsn** [comment]
> Note on the Brazilian ABNT2 layout, when typing the `"`character the expected behavior is that either you type a letter, which it adds an accent to (e.g. `"-e` produces: `é`), or you hit `enter` and it types the `"` (e.g. `"-enter` produces: `"`). May be related to #7 in how Zed currently doesn't hook into OS support for inserting symbols. Thank you to @loudermachine on the discord for explaining this.

I'm Brazilian and I use the US-international keyboard. So I need to type `'` + `e` = `é`. To insert the plain `'` or `"` I just type `"` + `<Space>` = `"`. Just commenting here to elaborate that to produce all plain symbols, we just need to type something after the symbol that not have any "produced" symbol. Like:
- `'` + `v` = `'v` (insert both `'` and `v`)
- `'` + `<Right>` = `'` (insert just `'` because `<Right>` is not an actual alpha symbol. The same will apply to `<Space>`, `<Up>`, `<Left>`, `<Enter>`)
- `'` + `<Backspace>` = `nothing`
- `^` + `1` = `ˆ1`
- `'` + `c` = `ç`
- `"` + `c` = `"c`
- `"` + `f` = `"f`

and so on...

Just to clarify what all keybinds do when we type aggregated symbols :)

**Comment by andremacola** [comment]
This issue is still a problem. Several fixes need to be made to US International keyboards and other languages. It's almost impossible to use the US International mode with quotes and accents.
