### ISSUE TITLE
Support user's default shell

### ISSUE THREAD

**Issue by gaetgu** [zed-industries/feedback#225]
When I open up the terminal, it uses `zsh` (macOS's default), but I have set the default to fish. This isn't *that* big of a deal, but I would really love it if the terminal used my default (fish) instead of mac's default (zsh).

**Environment:**
Zed 0.44.1 – /Applications/Zed.app
macOS 13.0
architecture arm64

**Comment by senevr** [comment]
> Fixed, will be in the next release!

Has that version been released? As I still have this problem on Zed 0.79.1

**Comment by senevr** [comment]
@mikayla-maki 

I'm not very technically experienced with these type of stuff so apologies if it turns out to be a simple mistake;

I'm on Air M1 macOS Ventura 13.3 and I recently switched from using ZSH to Fish, here are the two commands I ran in order to make Fish the default shell on my system:
``sudo bash -c 'echo $(which fish) >> /etc/shells'``
``chsh -s $(which fish)``
I got it from https://gist.github.com/idleberg/9c7aaa3abedc58694df5

``echo $SHELL`` outputs ``/opt/homebrew/bin/fish`` and everything works fine except with Zed. Tried restarting Zed and my computer but no luck, it just keeps defaulting to ZSH, i tried overriding the terminal option in settings to use ``"system"`` for ``shell`` but got no luck with that either. I don't know what else to tell you so if you need to know something else then let me know 👍

**Comment by mikayla-maki** [comment]
Ahh, I can reproduce the issue now. Thank you! :D

**Comment by mikayla-maki** [comment]
When using fish via the recommended fish installation method, it changes the $SHELL. For some reason, we don't have $SHELL in the Zed process environment. Have not dug further.
