### ISSUE TITLE
Terminal tab title changes while in other shells

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#226]
**Describe the bug**
The terminal tab's title changes from "Terminal" to the project directory path when in other shells.  I'm in Nushell in the screenshot below and after I run the first command after switching into Nushell, the tab title changes.
**To reproduce**

**Screenshots**
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/19867440/177570759-f590671a-415c-4deb-b8ce-6599fb338d59.png">

**Environment:**
Zed 0.44.1 – /Applications/Zed.app
macOS 12.4
architecture x86_64

**Comment by mikayla-maki** [comment]
Yeah, this is expected behavior. Alacritty and other terminal editors change the window title throughout execution so you know which window is which and I forward that to the tab. I particularly like this feature when running a long-living program (e.g. npm watch) as it shows the currently executing command in the title. 

That said, an issue with this feature is that working directory names are way too long. With my current shell it actually puts the entire prompt (including the user@host) up there too. I can see a use case for this, when you have a lot terminals open with some ssh-ing while others run long commands or whatnot, but it still looks strange and out of place. Unsure of how much leeway I have in controlling this behavior, but it does need to change somehow.

**Comment by JosephTLyons** [comment]
> Yeah, this is expected behavior. Alacritty and other terminal editors change the window title throughout execution so you know which window is which and I forward that to the tab text. I particularly like this feature when running a long-living program (e.g. npm watch) as it shows the currently executing command in the title.
> 
> That said, an issue with this feature is that working directory names are way too long. With my current shell it actually puts the entire prompt (including the user@host) up there too. I can see a use case for this, when you have a lot terminals open with some ssh-ing while others run long commands or whatnot, but it still looks strange and out of place. Unsure of how much leeway I have in controlling this behavior, but it does need to change somehow.

Since this behavior is expected, feel free to close this one, unless you want to repurpose the other items you mentioned surrounding the titles in the tab area.

**Comment by mikayla-maki** [comment]
Actually, on second thought, I'll close this as wont-fix, the issues with title formatting are a separate, deeper issue and this is expected behavior.
