### ISSUE TITLE
Allow project panel to be scrolled horizontally

### ISSUE THREAD

**Issue by maraisr** [zed-industries/feedback#241]
With a very deeply nested file tree, and a somewhat cozy viewport, file names cannot be read easily.

![image](https://user-images.githubusercontent.com/599459/177655736-4735e4a2-57c0-487c-ba17-586eddcd7862.png)

**Comment by as-cii** [comment]
We ended up merging a change that makes the project panel more compact, as opposed to making it scrollable. This is consistent with VS Code and from a UX standpoint it prevents issues when renaming a file with a long name, which would create two scrolling layers and make the behavior a bit confusing.

The fix for this will go out with the next release, thanks so much for the report!
