### ISSUE TITLE
Make error more apparent when hovering over it

### ISSUE THREAD

**Issue by Programatic** [zed-industries/feedback#242]
When an error is present, for instance a trailing comma in the settings.json, the error can be really hard to see. I eventually saw the issue at the bottom of the editor, but it simply looked like regular text. Perhaps changing the color to a red or prepending an ERROR: to make it much more clear that it is an error? Also, I tried hovering my mouse over it and nothing appeared to happen. If that is not yet implemented, perhaps it could be to also improve readability of errors?

**Comment by iamnbutler** [comment]
Are you using Rose Pine? This is an issue with this theme that I need to fix 😅

Rose Pine:
<img width="854" alt="CleanShot - 2022-07-07 at 08 59 51@2x" src="https://user-images.githubusercontent.com/1714999/177779462-32b3ba23-e724-4e85-8cc7-5501049d475d.png">

Andromeda:
<img width="855" alt="CleanShot - 2022-07-07 at 09 00 32@2x" src="https://user-images.githubusercontent.com/1714999/177779658-49a8bd4f-46ff-4f12-8460-c2b73adac6a7.png">

It is strange however that project diagnostics don't indicate there is an error here. Likely because `settings.json` isn't considered part of the project.

**Comment by as-cii** [comment]
Thanks for the feedback, @Programatic. In the latest version of Zed you can now hover over an error to display it, curious to hear what you think about it!
