### ISSUE TITLE
No difference between Iosevka and Iosevka extended.

### ISSUE THREAD

**Issue by TheFoolishPupil** [zed-industries/feedback#245]
**Describe the bug**
I'm attempting to set the buffer font to Iosevka Regular, as downloaded from https://typeof.net/Iosevka/. One of the reasons I like the font so much is its smaller than normal width, allowing me to see more of my code in less screen real estate. When I set the font to Iosevka Regular I see no difference from Iosevka Extended.

**To reproduce**
Download Iosevka and set the buffer_font_family to "Iosevka Regular" and see no noticeable difference.

**Expected behavior**
I expected the character width to be smaller than that of Iosevka Extended and Zed Mono.

**Screenshots**

**Environment:**
Copy & paste output of this command:
```
Zed 0.45.0 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64
```

**Comment by TheFoolishPupil** [comment]
I can now get the thinner Iosevka I am used to by setting the font to "Iosevka" which was giving me issues but works after leaving an unresponsive Zed application for about 30 minutes. see #246

**Comment by iamnbutler** [comment]
The issue I believe is you can only set a font family, not a specific weight. Due to Iosevka combining condensed and normal (or normal an extended, based on your config), both are not available. 

Depending on your variant of Iosevka, some variants treat "Normal" as extended. I only know this as Zed Mono/Sans actually use custom Iosevka builds :)

I've never heard anyone having the latter issue, thanks for opening an issue for that.

**Comment by iamnbutler** [comment]
I'll close this issue for now, but feel free to re-open if this didn't answer your question!
