### ISSUE TITLE
Zed's Linux/Windows build preview

### ISSUE THREAD

**Issue by urffsamhunt** [zed-industries/feedback#282]
I had the awesome chance of trying out the code editor but it seems that there are only Mac builds available right now, which is unfortunate for me since I am on Linux. When can we expect builds for Linux and Windows systems?

**Comment by Kethku** [comment]
Theres some more details here https://github.com/zed-industries/feedback/issues/174 going to close as repeat

**Comment by niccolox** [comment]
I have spent 5 minutes following broken links to vote for Linux and Windows support

I use Windows at work (no choice), do all my dev work on Dell XPS running Ubuntu and my creative work on Mac

I avoid vscode (its a MS trap) and Jetbrains and Sublime are my current tools, but I am REALLY REALLY open to paying for a working Linux alternative

**Comment by pmarreck** [comment]
Apple is slowly becoming developer-hostile (can't you feel it?), and I've been a Mac fan for... decades?... Yep, since 1984 (literally). But a Linux fan for about 1.5 years now or so. It's less user-friendly and less well-thought-out (it could use the same type of "love" usually given to Mac apps, basically!) but pretty much literally everything else is better on it, and I think it's because of everything being open-source.

Zed looks nice but frankly it's going to sink by tying itself to Apple's sinking desktop ship: https://www.forbes.com/sites/johnkoetsier/2023/04/10/apples-mac-shipments-plummeted-405-last-quarter-more-than-any-other-major-pc-maker/?sh=5ac943b91ce3

There seems to be a migration of other devs like me who are historically Mac fans but are getting fed up with Apple's increasingly-restrictive (and, as I said, developer-hostile) approach in each new OS release:

https://www.omglinux.com/devs-prefer-linux-to-mac-stackoverflow-survey/

https://markosaric.com/linux/

That said...

https://cfenollosa.com/blog/fed-up-with-the-mac-i-spent-six-months-with-a-linux-laptop-the-grass-is-not-greener-on-the-other-side.html

**Comment by pmarreck** [comment]
It's also... off-putting... in a really big way... to just lock down all the threads about this. What all this noise tells me is that there's a big space available to make a sweet editor on Linux.
