### ISSUE TITLE
Can not insert diacritics

### ISSUE THREAD

**Issue by belcar-s** [zed-industries/feedback#317]
I apologize if there’s already an issue open about this! I couldn’t find it, although #199 seems related. 

**Describe the bug**
I can not add diacritics to any character in the editor using my Spanish keyboard layout. 

**To reproduce**
Press the acute accent key followed by a vowel, like A. Observe that an alert sound is played, and then ‘a’, lacking the diacritical mark, appears. 

**Expected behavior**
á is inserted.

**Environment:**
```
Zed 0.47.1 – /Volumes/Zed/Zed.app 
macOS 12.4 
architecture arm64
```

**Comment by alevroub** [comment]
I can reproduce this using an US English keyboard layout. Though it seems like the problem is related to keyboard shortcuts bound to the option-key (in macOS at least).

– `option-b` should type `∫`, but moves the cursor to the beginning of the selected word
– `option-n` should type `˜` but only inputs `n`
– `option-d` should input `∂` but removes the next line

and so on.
