### ISSUE TITLE
Certain custom keybindings involving `shift` no longer work

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#419]
### Check for existing issues

- [X] Completed

### Describe the bug

I have been using these custom keybindings for a little while:

```json
"cmd-\\": "workspace::ToggleLeftSidebar",
"cmd-shift-|": "workspace::ToggleRightSidebar"
```

In a newer version, `"cmd-shift-|"` stopped working.  @mikayla-maki pointed out that keybindings now use the non-shifted form, so the binding would then be `cmd-shift-\\`, but this also didn't work.  Mikayla also mentioned that `ctrl-shift-`` no longer works.

### To reproduce

===

### Expected behavior

===

### Environment

Zed 0.50.0 – /Applications/Zed.app
macOS 12.4
architecture x86_64

**Comment by as-cii** [comment]
@JosephTLyons thanks! In this case, the key binding system interprets removes the `shift` modifier because it isn't an uppercase version of the character that was pressed. In other words, to make it work you'll need to specify:

```
"cmd-\\": "workspace::ToggleLeftSidebar",
"cmd-|": "workspace::ToggleRightSidebar"
```

I tested this locally and it works, maybe we could make it more intuitive but this is how the same key binding is resolved e.g. in Atom. VS Code maps it to `cmd-shift-\\` but I think that's a bit unintuitive with international keyboards, e.g. in the Swiss-French one where e.g. `cmd-shift-7` actually means `cmd-/`.

We should probably have a keybinding resolver that types the key binding you're holding at the moment on behalf of the user. Closing this for now, but please feel free to re-open if I missed something.

**Comment by JosephTLyons** [comment]
> @JosephTLyons thanks! In this case, the key binding system interprets removes the `shift` modifier because it isn't an uppercase version of the character that was pressed. In other words, to make it work you'll need to specify:
> 
> ```
> "cmd-\\": "workspace::ToggleLeftSidebar",
> "cmd-|": "workspace::ToggleRightSidebar"
> ```
> 
> I tested this locally and it works, maybe we could make it more intuitive but this is how the same key binding is resolved e.g. in Atom. VS Code maps it to `cmd-shift-\\` but I think that's a bit unintuitive with international keyboards, e.g. in the Swiss-French one where e.g. `cmd-shift-7` actually means `cmd-/`.
> 
> We should probably have a keybinding resolver that types the key binding you're holding at the moment on behalf of the user. Closing this for now, but please feel free to re-open if I missed something.

Using the keybinding you mentioned resolved the issue for me.  One thing I'm a bit confused about is I currently have another binding `"cmd-shift-d": "editor::SelectNext"` and it works with `shift`.  If I try to use `"cmd-D": "editor::SelectNext"`, it does not work.  I assumed I would need to change all of my keybindings that use `shift`.

**Comment by as-cii** [comment]
The underlying rationale is that we want `shift` to be present in the key binding only when it would output the uppercase variant of the pressed key stroke: the idea is that, in that case, `shift` is not being used to access a different key, but just as a modifier. Vice versa, we want to remove `shift` when the resulting character is completely different.

This behavior is consistent with Atom and Textmate, although I do think it'd be a lot easier if we had a key binding resolver that helps the user understand what key binding a certain keypress would resolve to.
