### ISSUE TITLE
Reliability and usefulness of telemetry

### ISSUE THREAD

**Issue by Atelier-Mirai** [zed-industries/feedback#549]
### Check for existing issues

- [X] Completed

The telemetry will be collecting some information.(Opening the app / Signing in / Opening and saving files. File extensions etc.)
In what way can we trust it?
How can we trust that the logs are not false? (It's easy to send source code, but hide it and show only the extension.)
Of course, I know that the Zed developers are great people and would never cheat.

### Describe the solution you'd like

Please explain in more detail why telemetry is useful for development. 
And I hope that unwanted users will reject telemetry.

**Comment by mikayla-maki** [comment]
In order to verify that Zed is behaving as expected, you can intercept network requests to api2.amplitude.com. I personally have pushed for this, specifically so that people can inspect and verify our telemetry without relying on our tools. 

We’re looking for this information so we can gauge usage, what kind of projects people are working on, and generally understand our product and our users. 

We will be adding settings to turn it off before beta

**Comment by MultisampledNight** [comment]
Unsuspecting third party: For actually intercepting the requests, ZAProxy will likely do a fine job.

**Comment by mikayla-maki** [comment]
I'm going to close this one for now, thank you for checking in on this :)
