### ISSUE TITLE
replace

### ISSUE THREAD

**Issue by ZPVIP** [zed-industries/feedback#603]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I can't find replace function.

### Describe the solution you'd like

replace is a must have feature

**Comment by JosephTLyons** [comment]
Hey @ZPVIP, we do have an issue for tracking this request.  Would you mind upvoting it?  Going to close this one in favor of that one.

- https://github.com/zed-industries/feedback/issues/58

**Comment by iamvoidcoder** [comment]
Hi. Why is this ticket closed as completed? Is the find and replace function implemented now? I keep bouncing back after each new build to check if find and replace in the current buffer (ideally also global find and replace in project folders) function has been implemented or not and it doesn't look like there is any replace facility to date. The only critical feature preventing to finally switch to otherwise great editor :(

**Comment by tra** [comment]
> Hey @ZPVIP, we do have an issue for tracking this request. Would you mind upvoting it? Going to close this one in favor of that one.
> 
> * https://github.com/zed-industries/feedback/issues/58

I think the correct URL is #58
