### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/feedback#66]

**Comment by JosephTLyons** [comment]
I recommend [Black](https://black.readthedocs.io/en/stable/) for Python code formatting

**Comment by maxbrunsfeld** [comment]
This will ship in Zed 0.40.

@JosephTLyons I think you're right about Black. I didn't include that in this first version, because up until now, we've been relying on language servers for code formatting. We do have it on our radar that we need to support separate code-formatting tools though (https://github.com/zed-industries/feedback/issues/91). People want this so that they can use Prettier with JS/TypeScript code.
