### ISSUE TITLE
rebranding or the new logo

### ISSUE THREAD

**Issue by yournumberone** [zed-industries/feedback#677]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

what do you think about the rebranding or the new logo? I really like your product, but the association with the conflict in Eastern Europe repels me.

### Describe the solution you'd like

new logo

**Comment by iamnbutler** [comment]
Hi there,

I was trying to find our previous response to this feedback, but I think that issue was before we moved to this repository.

The logo & branding in place has been static since we've started letting people use Zed around May of last year. It likely will be updated before Zed is released publically.

Apologies the current branding, or any unintentional associations it draws, makes you feel uncomfortable. I can personally note that it is unrelated to any existing imagery, political or otherwise. I can say this for sure because I made all the current assets, including the logo.

We are working on updated branding, which will likely include a new logo. We don't have a timeline to share on this now however. We'll share more when we have more to share.

Thanks for the feedback.
