### ISSUE TITLE
root-level setting tab_size won't work

### ISSUE THREAD

**Issue by exalted** [zed-industries/feedback#80]
When working with JavaScript the following `settings.json`…

```
{
    "tab_size": 4
}
```

… ☝️ this will not work (effective `tab_size` applied will be `2` regardless), whilst…

```
{
    "tab_size": 4,
    "language_overrides": {
        "JavaScript": {
            "tab_size": 4
        }
    }
}
```

… works. 🤷

**Comment by as-cii** [comment]
Okay so I believe this is actually a gotcha as opposed to being an actual defect. Specifically:

- When editing `settings.json` the `tab_size` is the default, e.g. 2
- Let's say we edit the `tab_size` and assign `4` to it
- Formatting is invoked before saving, so we will use the old `tab_size` (2) and format the document with that configuration
- Saving finally takes place, causing Zed to reload the settings
- If we were to save again, Zed would format the code with the new `tab_size` value

It's particularly confusing because we are editing the `settings.json` file itself so it is a bit of a chicken-and-egg problem. I am removing the `discussed` label from this so that we have a chance to talk about it again during the next weekly meeting. In the meantime, I am curious to hear thoughts on how to best accommodate for this quirk.

**Comment by exalted** [comment]
Hmm, I am not sure if we're on the same wave length, @as-cii … This is about JavaScript. What I am suggesting is that `tab_size` at the root-level doesn't apply to `*.js` files, vs the language override does. Makes sense?
