### ISSUE TITLE
Confirm Quit dialog

### ISSUE THREAD

**Issue by aleksa-stajcic** [zed-industries/feedback#866]
### Check for existing issues

- [X] Completed

### Describe the feature

When using Cmd-Q to quit there is no dialog to confirm if you want to quit. I think it would be a nice feature to have, as someone who constantly misses key bindings.

**Comment by caius** [comment]
My usual trick remapping this to cmd-alt-q using macOS doesn't appear to work here either. Zed still responds to cmd-q. I suspect because the keymap in Zed is listening as well so whilst the system isn't selecting Quit from the app menu, Zed is still "hearing" cmd-q and invoking `zed::Quit` as per the [default keymap](https://zed.dev/ref/default.json)

I remap a bunch of apps in the Settings (nee System Preferences) Keyboard PrefPane, under "Keyboard Shortcuts" to have cmd-alt-q trigger their Quit menu item.[^1] See screenshot for details.

<img width="827" alt="Screenshot 2023-01-18 at 01 18 50" src="https://user-images.githubusercontent.com/696/213057271-de8cc132-1a24-4781-b3e6-a240928a8cf6.png">

I'd expect Zed to stop responding to cmd-q at that point, as you can see the menu item has the overridden key combination against it.

<img width="247" alt="Screenshot 2023-01-18 at 01 23 26" src="https://user-images.githubusercontent.com/696/213057873-2cd140fc-5565-48e4-944a-3961c9fca70b.png">

If I also add `"cmd-q": "zed::ShowAll"` to my global bindings in the keymap, then Zed happily stays active if I hit cmd-q whilst it's running. (The JSON requires a string as the value, so choosing a noop action is the only way I could see to "disable" a default keymap.)

[^1]: Most apps have "Quit $appName" as the menu item. Zed is simply "Quit" which should probably change on macOS for convention with other apps on the system. I wonder if that's part of the Human Interface Guidelines in fact 🤔
